%input = phi double [3.5, %entry], [%next_input, %loop]
%temp1 = fadd double %input, 1.0
%temp2 = fadd double %temp1, 1.0
%temp3 = fadd double %temp2, 1.0
%result1 = fcmp olt double %input, %temp1
%result2 = fcmp olt double %temp1, %temp2
%result3 = fcmp olt double %temp2, %temp3
%result4 = fcmp olt double %temp3, %input
%result1_int = zext i1 %result1 to i64
%result2_int = zext i1 %result2 to i64
%result3_int = zext i1 %result3 to i64
%result4_int = zext i1 %result4 to i64
%sum1 = add i64 %sum, %result1_int
%sum2 = add i64 %sum1, %result2_int
%sum3 = add i64 %sum2, %result3_int
%next_sum = add i64 %sum3, %result4_int
%diff = fsub double %temp2, %temp1
%next_input = fadd double %temp3, %diff 