%input = phi i64 [42, %entry], [%next_input, %loop]
%temp1 = add i64 %input, 1
%temp2 = add i64 %temp1, 1
%temp3 = add i64 %temp2, 1
%result = uitofp i64 %input to double
%result_int = fptosi double %result to i64
%result_int2 = fptosi double %result to i64
%result_int3 = fptosi double %result to i64
%result_int4 = fptosi double %result to i64
%sum1 = add i64 %sum, %result_int
%sum2 = add i64 %sum1, %result_int2
%sum3 = add i64 %sum2, %result_int3
%next_sum = add i64 %sum3, %result_int4
%diff = sub i64 %temp2, %temp1
%next_input = add i64 %temp3, %diff 